#!/bin/sh

# Ensure that the script is run as root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi


# Load the configuration
if [ -f "/etc/default/shared-folders" ]; then
    . /etc/default/shared-folders
else
    echo "Error: /etc/default/shared-folders not found." 1>&2
    exit 1
fi

# Set default values in case the variables are not present in the config
SHARE_GROUPS=${SHARE_GROUPS:-"teachers"}
SHARE_DIR=${SHARE_DIR:-"/home/Shared"}
PUBLIC_DIR=${PUBLIC_DIR:-"/home/Shared/Public"}

usage() {
    echo "Usage: $0"
}

# Create the symlinks for the folders
create_symlinks() {
    echo "Creating symlinks for users..."
    for user_dir in /home/*; do
        user=$(basename "$user_dir")
        if [[ ! -d "$user_dir" ]] || [[ "$user" == "Shared" ]]; then
            continue
        fi

        # Ensure the Public directory exists
        mkdir -p "$user_dir/Public"

        # Create symlink to Public folder
        ln -sf "$PUBLIC_DIR" "$user_dir/Public/Public"

        # Create symlinks for each group
        for group in $SHARE_GROUPS; do
            if [ -d "$SHARE_DIR/$group" ]; then
                ln -sf "$SHARE_DIR/$group" "$user_dir/Public/$group"
            fi
        done
    done
    echo "Symlinks created successfully."
}

# Check for the arguments
set -e
if [ $# -ne 0 ]; then
    usage
    exit 1
fi

# Run the symlinks creation
create_symlinks
