name: Build Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper

    - name: Build Debian Package
      run: |
        # Define variables for paths
        OUTPUT_DIR=/tmp/debian-package
        BUILD_DIR="$GITHUB_WORKSPACE/build-dir"
        SOURCE_DIR="$GITHUB_WORKSPACE/sch-scripts"
        PACKAGE_NAME="sch-scripts"
        
        mkdir -p "$OUTPUT_DIR"
        cd "$GITHUB_WORKSPACE"
        VERSION=$(dpkg-parsechangelog --show-field Version | sed 's/-.*//')
        TARBALL="${PACKAGE_NAME}_${VERSION}.orig.tar.gz"
        git archive --format=tar.gz --prefix="${PACKAGE_NAME}/" -o "$TARBALL" HEAD
        mkdir -p "$BUILD_DIR"
        mv "$TARBALL" "$BUILD_DIR"
        cp -r "$SOURCE_DIR" "$BUILD_DIR"
        cd "$BUILD_DIR/${PACKAGE_NAME}"
        debuild -us -uc
        find .. -name "*.deb" -exec mv {} "$OUTPUT_DIR/" \;

    - name: List Directories
      run: |
        echo "Output Directory:"
        ls -al "$OUTPUT_DIR"
        echo "GitHub Workspace:"
        ls -al "$GITHUB_WORKSPACE"
        echo "Build Directory:"
        ls -al "$GITHUB_WORKSPACE/build-dir"
        echo "Build Directory/Package:"
        ls -al "$GITHUB_WORKSPACE/build-dir/${PACKAGE_NAME}"

    - name: Upload Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: sch-scripts-deb
        path: "$OUTPUT_DIR/*.deb"
        if-no-files-found: error
        compression-level: 6
        overwrite: false
        include-hidden-files: false
