name: Build Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper

    - name: Build Debian Package
      run: |
        mkdir -p /tmp/debian-package
        cd $GITHUB_WORKSPACE
        VERSION=$(dpkg-parsechangelog --show-field Version | sed 's/-.*//')
        TARBALL="sch-scripts_${VERSION}.orig.tar.gz"
        git archive --format=tar.gz --prefix=sch-scripts/ -o $TARBALL HEAD
        # Create a temporary directory to build the package in
        BUILD_DIR="$GITHUB_WORKSPACE/build-dir"
        mkdir -p "$BUILD_DIR"
        # Move the source tarball to the build directory.  debuild expects it in the parent
        mv "$TARBALL" "$BUILD_DIR"
        # Copy the source code to the build directory.
        cp -r sch-scripts "$BUILD_DIR"
        # Change to the directory containing the debian directory.
        cd "$BUILD_DIR/sch-scripts"
        # Run debuild from the correct location.
        debuild -us -uc
        # Move the resulting .deb files to the desired output directory
        find .. -name "*.deb" -exec mv {} /tmp/debian-package/ \;

    - name: List Directories
      run: |
        ls -al /tmp/debian-package
        ls -al $GITHUB_WORKSPACE
        ls -al $GITHUB_WORKSPACE/build-dir # Add this line to list the build dir
        ls -al $GITHUB_WORKSPACE/build-dir/sch-scripts # Add this line

    - name: Upload Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: sch-scripts-deb
        path: /tmp/debian-package/*.deb
        if-no-files-found: error
        compression-level: 6
        overwrite: false
        include-hidden-files: false
