name: Build Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper

    - name: Create source tarball
      run: |
        cd $GITHUB_WORKSPACE
        VERSION=$(dpkg-parsechangelog --show-field Version | sed 's/-.*//')
        TARBALL="../sch-scripts_${VERSION}.orig.tar.gz"
        git archive --format=tar.gz --prefix=sch-scripts/ -o $TARBALL HEAD

    - name: Build Debian package
      run: |
        cd $GITHUB_WORKSPACE
        debuild -us -uc

    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: sch-scripts-deb
        path: artifacts/sch-scripts.deb
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.13.2/x64
        PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.13.2/x64/lib/pkgconfig
        Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.2/x64
        Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.2/x64
        Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.2/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.13.2/x64/lib
